### ISSUE TITLE
Keyerror: wmoUnit:degC

### ISSUE THREAD

**Issue by firstof9** [MatthewFlamm/pynws#58]
Looks like they changed the format again?

```log
2021-10-05 08:15:51 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nws platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 462, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 273, in state
    value = self.native_value
  File "/config/custom_components/nws/sensor.py", line 82, in native_value
    value = self._nws.observation.get(self.entity_description.key)
  File "/usr/local/lib/python3.9/site-packages/pynws/simple_nws.py", line 261, in observation
    data[obs] = unit_conversion[obs_item[1]](obs_item[0])
KeyError: 'wmoUnit:degC'
```

**Comment by MatthewFlamm** [comment]
Looks like you are using 1.3.0?  If so, can you try 1.3.1?

I tried to make this more robust and only look for `degC` in 1.3.1

**Comment by firstof9** [comment]
Odd, perhaps HA didn't upgrade the library
Note: 2021.10.0b6 is when this regressed, b4 was fine.

EDIT: from inside the container:
```
bash-5.1# pip3 freeze | grep pynws
pynws==1.3.0
```

**Comment by firstof9** [comment]
False alarm, I had it added under a custom_component for troubleshooting previously and forgot.

**Comment by MatthewFlamm** [comment]
Looks like NWS is flip flopping usage of these values.  Hopefully they won't decide to switch to `wmoUnit:degreeC` in the future.
